[project]
name = "noctisdice"
version = "4.0.0-rc.4"
description = "夜骰核心组件--莲特化版"
authors = [
    {name = "fu050409",email = "fu050409@163.com"},
    {name = "BegoniaHe",email = "tianyihebegonia1005@gmail.com"}
]
license = "Apache-2.0"
readme = "README.md"

[requirements]
coc = "0.1.0-rc.1"
ndice = "0.1.0-rc.1"

[dependencies]
psutil = "*"
diceutils = "*"
